name: Question
description: Ask a question about Scruff
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: What version of scruff are you using? (see `scruff version`)
      placeholder: e.g., scruff 0.9.3 (90589372d 2025-01-23)
    validations:
      required: false
